In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
movie_data = pd.read_csv("movie.csv")

In [3]:
print(movie_data)

     Collection  Marketing expense  Production expense  Multiplex coverage  \
0         48000            20.1264               59.62               0.462   
1         43200            20.5462               69.14               0.531   
2         69400            20.5458               69.14               0.531   
3         66800            20.6474               59.36               0.542   
4         72400            21.3810               59.36               0.542   
..          ...                ...                 ...                 ...   
501       44800            21.2526               78.86               0.427   
502       41200            20.9054               78.86               0.427   
503       47800            21.2152               78.86               0.427   
504       44000            22.1918               78.86               0.427   
505       38000            20.9482               78.86               0.427   

        Budget  Movie_length  Lead_ Actor_Rating  Lead_Actress_

In [4]:
movie_data.head()

Collection  Marketing expense  Production expense  Multiplex coverage  \
0       48000            20.1264               59.62               0.462   
1       43200            20.5462               69.14               0.531   
2       69400            20.5458               69.14               0.531   
3       66800            20.6474               59.36               0.542   
4       72400            21.3810               59.36               0.542   

      Budget  Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  \
0  36524.125         138.7               7.825                8.095   
1  35668.655         152.4               7.505                7.650   
2  39912.675         134.6               7.485                7.570   
3  38873.890         119.3               6.895                7.035   
4  39701.585         127.7               6.920                7.070   

   Director_rating  Producer_rating  Critic_rating  Trailer_views  \
0            7.910            7.995           7.94         527367   
1            7.440            7.470           7.44         494055   
2            7.495            7.515           7.44         547051   
3            6.920            7.020           8.26         516279   
4            6.815            7.070           8.26         531448   

  3D_available  Time_taken  Twitter_hastags     Genre  Avg_age_actors  \
0          YES      109.60          223.840  Thriller              23   
1           NO      146.64          243.456     Drama              42   
2           NO      147.88         2022.400    Comedy              38   
3          YES      185.36          225.344     Drama              45   
4           NO      176.48          225.792     Drama              55   

  MPAA_film_rating  Num_multiplex  Start_Tech_Oscar  
0               PG            494                 0  
1               PG            462                 1  
2               PG            458                 0  
3               PG            472                 0  
4               PG            395                 0

In [5]:
movie_data.shape

(506, 20)

In [6]:
movie_data.describe()

Collection  Marketing expense  Production expense  \
count     506.000000         506.000000          506.000000   
mean    45057.707510          92.270471           77.273557   
std     18364.351764         172.030902           13.720706   
min     10000.000000          20.126400           55.920000   
25%     34050.000000          21.640900           65.380000   
50%     42400.000000          25.130200           74.380000   
75%     50000.000000          93.541650           91.200000   
max    100000.000000        1799.524000          110.480000   

       Multiplex coverage        Budget  Movie_length  Lead_ Actor_Rating  \
count          506.000000    506.000000    506.000000          506.000000   
mean             0.445305  34911.144022    142.074901            8.014002   
std              0.115878   3903.038232     28.148861            1.054266   
min              0.129000  19781.355000     76.400000            3.840000   
25%              0.376000  32693.952500    118.525000            7.316250   
50%              0.462000  34488.217500    151.000000            8.307500   
75%              0.551000  36793.542500    167.575000            8.865000   
max              0.615000  48772.900000    173.500000            9.435000   

       Lead_Actress_rating  Director_rating  Producer_rating  Critic_rating  \
count           506.000000       506.000000       506.000000     506.000000   
mean              8.185613         8.019664         8.190514       7.810870   
std               1.054290         1.059899         1.049601       0.659699   
min               4.035000         3.840000         4.030000       6.600000   
25%               7.503750         7.296250         7.507500       7.200000   
50%               8.495000         8.312500         8.465000       7.960000   
75%               9.030000         8.883750         9.030000       8.260000   
max               9.540000         9.425000         9.635000       9.400000   

       Trailer_views  Time_taken  Twitter_hastags  Avg_age_actors  \
count     506.000000  494.000000       506.000000      506.000000   
mean   449860.715415  157.391498       260.832095       39.181818   
std     68917.763145   31.295161       104.779133       12.513697   
min    212912.000000    0.000000       201.152000        3.000000   
25%    409128.000000  132.300000       223.796000       28.000000   
50%    462460.000000  160.000000       254.400000       39.000000   
75%    500247.500000  181.890000       283.416000       50.000000   
max    567784.000000  217.520000      2022.400000       60.000000   

       Num_multiplex  Start_Tech_Oscar  
count     506.000000        506.000000  
mean      545.043478          0.454545  
std       106.332889          0.498422  
min       333.000000          0.000000  
25%       465.000000          0.000000  
50%       535.500000          0.000000  
75%       614.750000          1.000000  
max       868.000000          1.000000

In [7]:
movie_data.Time_taken = movie_data.Time_taken.fillna(movie_data.Time_taken.mean)

In [8]:
movie_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Collection           506 non-null    int64  
 1   Marketing expense    506 non-null    float64
 2   Production expense   506 non-null    float64
 3   Multiplex coverage   506 non-null    float64
 4   Budget               506 non-null    float64
 5   Movie_length         506 non-null    float64
 6   Lead_ Actor_Rating   506 non-null    float64
 7   Lead_Actress_rating  506 non-null    float64
 8   Director_rating      506 non-null    float64
 9   Producer_rating      506 non-null    float64
 10  Critic_rating        506 non-null    float64
 11  Trailer_views        506 non-null    int64  
 12  3D_available         506 non-null    object 
 13  Time_taken           506 non-null    object 
 14  Twitter_hastags      506 non-null    float64
 15  Genre                506 non-null    obj

In [9]:
movie_data.head()

Collection  Marketing expense  Production expense  Multiplex coverage  \
0       48000            20.1264               59.62               0.462   
1       43200            20.5462               69.14               0.531   
2       69400            20.5458               69.14               0.531   
3       66800            20.6474               59.36               0.542   
4       72400            21.3810               59.36               0.542   

      Budget  Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  \
0  36524.125         138.7               7.825                8.095   
1  35668.655         152.4               7.505                7.650   
2  39912.675         134.6               7.485                7.570   
3  38873.890         119.3               6.895                7.035   
4  39701.585         127.7               6.920                7.070   

   Director_rating  Producer_rating  Critic_rating  Trailer_views  \
0            7.910            7.995           7.94         527367   
1            7.440            7.470           7.44         494055   
2            7.495            7.515           7.44         547051   
3            6.920            7.020           8.26         516279   
4            6.815            7.070           8.26         531448   

  3D_available Time_taken  Twitter_hastags     Genre  Avg_age_actors  \
0          YES      109.6          223.840  Thriller              23   
1           NO     146.64          243.456     Drama              42   
2           NO     147.88         2022.400    Comedy              38   
3          YES     185.36          225.344     Drama              45   
4           NO     176.48          225.792     Drama              55   

  MPAA_film_rating  Num_multiplex  Start_Tech_Oscar  
0               PG            494                 0  
1               PG            462                 1  
2               PG            458                 0  
3               PG            472                 0  
4               PG            395                 0

In [12]:
movie_data['Ratings'] = (movie_data.Lead_Actress_rating + movie_data.Director_rating +
                         movie_data.Producer_rating + movie_data.Critic_rating + movie_data.Critic_rating)/5

In [13]:
movie_data.head()

Collection  Marketing expense  Production expense  Multiplex coverage  \
0       48000            20.1264               59.62               0.462   
1       43200            20.5462               69.14               0.531   
2       69400            20.5458               69.14               0.531   
3       66800            20.6474               59.36               0.542   
4       72400            21.3810               59.36               0.542   

      Budget  Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  \
0  36524.125         138.7               7.825                8.095   
1  35668.655         152.4               7.505                7.650   
2  39912.675         134.6               7.485                7.570   
3  38873.890         119.3               6.895                7.035   
4  39701.585         127.7               6.920                7.070   

   Director_rating  Producer_rating  ...  Trailer_views  3D_available  \
0            7.910            7.995  ...         527367           YES   
1            7.440            7.470  ...         494055            NO   
2            7.495            7.515  ...         547051            NO   
3            6.920            7.020  ...         516279           YES   
4            6.815            7.070  ...         531448            NO   

  Time_taken Twitter_hastags     Genre Avg_age_actors  MPAA_film_rating  \
0      109.6         223.840  Thriller             23                PG   
1     146.64         243.456     Drama             42                PG   
2     147.88        2022.400    Comedy             38                PG   
3     185.36         225.344     Drama             45                PG   
4     176.48         225.792     Drama             55                PG   

  Num_multiplex  Start_Tech_Oscar  Ratings  
0           494                 0    7.976  
1           462                 1    7.488  
2           458                 0    7.492  
3           472                 0    7.499  
4           395                 0    7.495  

[5 rows x 21 columns]

In [14]:
del movie_data["Lead_ Actor_Rating"] #X

In [15]:
del movie_data["Lead_Actress_rating"]

In [16]:
del movie_data["Director_rating"]

In [17]:
del movie_data["Producer_rating"]

In [18]:
del movie_data["Critic_rating"]

In [19]:
movie_data.head()

Collection  Marketing expense  Production expense  Multiplex coverage  \
0       48000            20.1264               59.62               0.462   
1       43200            20.5462               69.14               0.531   
2       69400            20.5458               69.14               0.531   
3       66800            20.6474               59.36               0.542   
4       72400            21.3810               59.36               0.542   

      Budget  Movie_length  Trailer_views 3D_available Time_taken  \
0  36524.125         138.7         527367          YES      109.6   
1  35668.655         152.4         494055           NO     146.64   
2  39912.675         134.6         547051           NO     147.88   
3  38873.890         119.3         516279          YES     185.36   
4  39701.585         127.7         531448           NO     176.48   

   Twitter_hastags     Genre  Avg_age_actors MPAA_film_rating  Num_multiplex  \
0          223.840  Thriller              23               PG            494   
1          243.456     Drama              42               PG            462   
2         2022.400    Comedy              38               PG            458   
3          225.344     Drama              45               PG            472   
4          225.792     Drama              55               PG            395   

   Start_Tech_Oscar  Ratings  
0                 0    7.976  
1                 1    7.488  
2                 0    7.492  
3                 0    7.499  
4                 0    7.495

In [23]:
X = movie_data[['Budget']]

In [24]:
Y = movie_data['Start_Tech_Oscar']

In [25]:
X.head()

Budget
0  36524.125
1  35668.655
2  39912.675
3  38873.890
4  39701.585

In [26]:
Y.head()

0    0
1    1
2    0
3    0
4    0
Name: Start_Tech_Oscar, dtype: int64

In [27]:
from sklearn.linear_model import LogisticRegression

In [28]:
classification = LogisticRegression()

In [29]:
classification.fit(X,Y)

LogisticRegression()

In [30]:
classification.coef_

array([[-4.98636792e-06]])

In [31]:
classification.intercept_

array([-1.61123752e-10])

In [33]:
import statsmodels.api as stats

In [34]:
X_const = stats.add_constant(x)

In [35]:
X_const.head()

const     Budget
0    1.0  36524.125
1    1.0  35668.655
2    1.0  39912.675
3    1.0  38873.890
4    1.0  39701.585

In [37]:
import statsmodels.discrete.discrete_model as sm

In [39]:
logit = sm.Logit(Y,X_const).fit()

Optimization terminated successfully.
         Current function value: 0.688641
         Iterations 4


In [40]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:       Start_Tech_Oscar   No. Observations:                  506
Model:                          Logit   Df Residuals:                      504
Method:                           MLE   Df Model:                            1
Date:                Thu, 09 Feb 2023   Pseudo R-squ.:               0.0005348
Time:                        00:44:46   Log-Likelihood:                -348.45
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                    0.5414
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.6707      0.805     -0.833      0.405      -2.249       0.908
Budget      1.399e-05   2.29e-05      0.610      0.542   -3.09e-05    5.89e-05
==============================================================================
"""

In [70]:
from sklearn.metrics import confusion_matrix

In [60]:
movie_data.head()

Collection  Marketing expense  Production expense  Multiplex coverage  \
0       48000            20.1264               59.62               0.462   
1       43200            20.5462               69.14               0.531   
2       69400            20.5458               69.14               0.531   
3       66800            20.6474               59.36               0.542   
4       72400            21.3810               59.36               0.542   

      Budget  Movie_length  Trailer_views 3D_available Time_taken  \
0  36524.125         138.7         527367          YES      109.6   
1  35668.655         152.4         494055           NO     146.64   
2  39912.675         134.6         547051           NO     147.88   
3  38873.890         119.3         516279          YES     185.36   
4  39701.585         127.7         531448           NO     176.48   

   Twitter_hastags     Genre  Avg_age_actors MPAA_film_rating  Num_multiplex  \
0          223.840  Thriller              23               PG            494   
1          243.456     Drama              42               PG            462   
2         2022.400    Comedy              38               PG            458   
3          225.344     Drama              45               PG            472   
4          225.792     Drama              55               PG            395   

   Start_Tech_Oscar  Ratings  
0                 0    7.976  
1                 1    7.488  
2                 0    7.492  
3                 0    7.499  
4                 0    7.495

### LDA

In [62]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [63]:
cls = LinearDiscriminantAnalysis()


In [65]:
cls.fit(X,Y)

LinearDiscriminantAnalysis()

In [66]:
y_pred = cs.predict(X)

In [67]:
y_pred 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [71]:
confusion_matrix(Y,y_pred)

array([[274,   2],
       [229,   1]], dtype=int64)

In [72]:
from sklearn.model_selection import train_test_split

In [73]:
xtrain,xtest,ytrain,ytest = train_test_split(X,Y,test_size=0.2,random_state=0)

In [74]:
print(xtrain.shape,xtest.shape,ytrain.shape,ytest.shape)

(404, 1) (102, 1) (404,) (102,)


In [76]:
logistic = LogisticRegression()

In [77]:
logistic.fit(xtrain,ytrain)

LogisticRegression()

In [79]:
y_pred = logistic.predict(xtest)

In [80]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [81]:
confusion_matrix(ytest,y_pred)

array([[58,  0],
       [44,  0]], dtype=int64)

In [82]:
accuracy_score(ytest,y_pred)

0.5686274509803921

In [54]:
x = movie_data.loc[:,movie_data.columns!='Start_Tech_Oscar']

In [55]:
y = movie_data['Start_Tech_Oscar']

In [56]:
x.head()

Collection  Marketing expense  Production expense  Multiplex coverage  \
0       48000            20.1264               59.62               0.462   
1       43200            20.5462               69.14               0.531   
2       69400            20.5458               69.14               0.531   
3       66800            20.6474               59.36               0.542   
4       72400            21.3810               59.36               0.542   

      Budget  Movie_length  Trailer_views 3D_available Time_taken  \
0  36524.125         138.7         527367          YES      109.6   
1  35668.655         152.4         494055           NO     146.64   
2  39912.675         134.6         547051           NO     147.88   
3  38873.890         119.3         516279          YES     185.36   
4  39701.585         127.7         531448           NO     176.48   

   Twitter_hastags     Genre  Avg_age_actors MPAA_film_rating  Num_multiplex  \
0          223.840  Thriller              23               PG            494   
1          243.456     Drama              42               PG            462   
2         2022.400    Comedy              38               PG            458   
3          225.344     Drama              45               PG            472   
4          225.792     Drama              55               PG            395   

   Ratings  
0    7.976  
1    7.488  
2    7.492  
3    7.499  
4    7.495

In [57]:
y.head()

0    0
1    1
2    0
3    0
4    0
Name: Start_Tech_Oscar, dtype: int64

In [58]:
from sklearn.linear_model import LogisticRegression

In [59]:
classification = LogisticRegression()

In [53]:
classification.fit(x,y)

ValueError: could not convert string to float: 'YES'

In [49]:
classification.coef_

array([[-4.98636792e-06]])

In [50]:
classification.intercept_

array([-1.61123752e-10])

In [51]:
import statsmodels.api as stats